apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo
  name: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dso-demo
    spec:
      automountServiceAccountToken: false
      serviceAccountName: dso-demo
      containers:
      - image: albertgoma/dso-demo
        name: dso-demo
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: tmp
            mountPath: /tmp
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 11000
      volumes:
        - name: tmp
          emptyDir: {}
status: {}
